version: 0.2

env:
  variables:
    bucket_name: "medicall-migration"
    LC_CTYPE: "C.UTF-8"
    #cloudfront_distribution_id: "E10GQXPX7YHHWD"

phases:
  install:
    commands:
      #- gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist
      - bundle update
      - bundle install
  build:
    commands:
      - echo "******** Logs copying files to S3 ******" > s3-log.txt

      - echo "******** Building Jekyll site ********"
      - jekyll build

      - echo "******** Remove extension from files before deploying *********"
      - find . ! -iname 'index.html' -iname '*.html' -type f | while read NAME ; do mv "${NAME}" "${NAME%.html}"; done;

      - echo "******** Copying files to S3 *********"
      - aws s3 sync _site/ s3://${bucket_name}/ --exclude "*" --include "*.*" --cache-control max-age=2592000 --delete --size-only | tee -a s3-log.txt

      - echo "******** Copying files with content type... *********"
      - aws s3 sync _site/ s3://${bucket_name}/ --exclude "*.*" --content-type text/html --cache-control max-age=86400 --delete --size-only | tee -a s3-log.txt

  post_build:
    commands:
      # - echo "******** Invalidate CloudFront Only modified fields ********"
      # - aws configure set preview.cloudfront true
      # - sh s3-script.sh

      # - echo "******** Set Cache-Control ********"
      # invalidate files with extention
      # - aws s3 sync _site/ s3://${bucket_name}/ --exclude "*" --include "*.*" --cache-control max-age=2592000 --delete --size-only

      # invalidate files without extention
      # - aws s3 sync _site/ s3://${bucket_name}/ --exclude "*.*" --content-type text/html --cache-control max-age=86400 --delete --size-only
