version: 0.2

env:
  variables:
    bucket_name: "medicall-migration"
    LANG: "he_IL.UTF-8"
    LANGUAGE: "he_IL.UTF-8"
    LC_CTYPE: "C.UTF-8"
    #cloudfront_distribution_id: "E10GQXPX7YHHWD"

phases:
  install:
    commands:
      - locale

#      - echo "***** install jekyll *****"
#      - gem install jekyll

      - echo "***** bundle install *****"
      - bundle update
      - bundle install

  build:
    commands:
      - jekyll build

  post_build:
    commands:
      - echo "postbuild"